# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20161108_0339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ('title',)},
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
