# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_auto_20161108_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='films',
            field=models.ManyToManyField(to='films.Film'),
        ),
    ]
